name: 'GitHub Secret Extractor'
description: 'Get the plain text value of a GitHub secret'
branding:
  icon: 'key'  
  color: 'orange'
inputs:
  secret: 
    description: 'The secret to extract'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
